# Generated by Django 2.1.5 on 2020-02-26 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='author',
        ),
    ]
