# Generated by Django 2.1.5 on 2020-02-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_remove_route_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='publish',
            field=models.BooleanField(choices=[(True, 'public'), (False, 'not public')], default=False),
        ),
    ]
