# Generated by Django 2.1.5 on 2019-02-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sum', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('creaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
