# Generated by Django 2.1.5 on 2019-04-09 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190409_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='email',
        ),
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
    ]
