# Generated by Django 2.1.5 on 2019-06-03 10:20

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190522_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=post.models.get_image_filename, verbose_name='Image'),
        ),
    ]
