# Generated by Django 2.1.5 on 2019-06-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20190603_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
