# Generated by Django 2.1.5 on 2019-06-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='summary',
        ),
    ]
