# Generated by Django 2.1.5 on 2019-04-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
