# Generated by Django 2.1.5 on 2019-08-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
