# Generated by Django 2.1.5 on 2019-04-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20190409_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.BooleanField(choices=[('public', True), ('not public', False)], default=False),
        ),
    ]
