# Generated by Django 2.1.5 on 2019-04-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.BooleanField(choices=[(True, 'public'), (False, 'not public')], default=False),
        ),
    ]
